---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: raj-eks
  region: us-east-1
  tags:
    project: linkedin-learning

nodeGroups:
  - name: worker-node
    instanceType: m5.large
    desiredCapacity: 3